### ISSUE TITLE
pre-build binary in release

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/seektime#4]
Can a release also include a pre-build binary ? we need this to create a runtime update package for zos so we can include both the new version of seektime and the code to handle it to running machines

Please check my comment here
https://github.com/threefoldtech/zos/pull/2023#issuecomment-1686272264

**Comment by maxux** [comment]
Implemented https://github.com/threefoldtech/seektime/commit/98be93d9d609c5397c85abd057902c3e23a3f1d7
Static build via alpine :)
